import { ArrowRight, Mail, MessageCircle, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import MainLayout from '../../layouts/MainLayout'
import { apiPost } from '../../lib/api'

export default function Contact() {
  const [submitted, setSubmitted] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setSending(true); setError(''); const form = new FormData(event.currentTarget); try { await apiPost('/api/contact', { name: form.get('name'), email: form.get('email'), website: form.get('website'), message: form.get('message') }); setSubmitted(true) } catch (requestError) { setError(requestError.message) } finally { setSending(false) } }
  return <MainLayout><main><section className="warm-grid px-6 pb-16 pt-14 sm:pt-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-stone-500">LET’S BUILD YOUR GROWTH SYSTEM</p><h1 className="display-type mt-4 max-w-5xl text-[clamp(3.5rem,9vw,8rem)] font-normal leading-[.88]">Start with a conversation.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-stone-700">Tell us about your website, growth goals, and current challenges. We will help you choose the right Growth OS workflow.</p></div></section>
    <section className="bg-white px-6 py-16"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><aside><h2 className="text-2xl font-bold">What happens next</h2><div className="mt-6 space-y-6 text-stone-600"><p className="flex gap-3"><MessageCircle className="shrink-0 text-stone-500" />We learn about your goals and current marketing stack.</p><p className="flex gap-3"><ShieldCheck className="shrink-0 text-stone-500" />We recommend a safe, approval-led workflow for your team.</p><p className="flex gap-3"><Mail className="shrink-0 text-stone-500" />We respond within one business day.</p></div></aside>{submitted ? <div className="panel p-8"><h2 className="text-2xl font-bold">Thanks — your enquiry was sent.</h2><p className="mt-3 leading-7 text-stone-600">Our team will follow up using the email address you provided.</p><button type="button" onClick={() => setSubmitted(false)} className="mt-6 font-semibold text-stone-500">Send another enquiry</button></div> : <form onSubmit={submit} className="panel grid gap-5 p-6 sm:grid-cols-2"><label className="text-sm font-semibold">Name<input required name="name" className="mt-2 w-full rounded-xl border border-stone-200 bg-white px-3 py-3 font-normal outline-none focus:border-lime-500 focus:ring-2 focus:ring-lime-100" placeholder="Your name" /></label><label className="text-sm font-semibold">Work email<input required name="email" type="email" className="mt-2 w-full rounded-xl border border-stone-200 bg-white px-3 py-3 font-normal outline-none focus:border-lime-500 focus:ring-2 focus:ring-lime-100" placeholder="you@company.com" /></label><label className="text-sm font-semibold sm:col-span-2">Website<input name="website" type="url" className="mt-2 w-full rounded-xl border border-stone-200 bg-white px-3 py-3 font-normal outline-none focus:border-lime-500 focus:ring-2 focus:ring-lime-100" placeholder="https://yourwebsite.com" /></label><label className="text-sm font-semibold sm:col-span-2">How can Growth OS help?<textarea required name="message" rows="5" className="mt-2 w-full resize-y rounded-xl border border-stone-200 bg-white px-3 py-3 font-normal outline-none focus:border-lime-500 focus:ring-2 focus:ring-lime-100" placeholder="Tell us about your goal or challenge" /></label>{error && <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 sm:col-span-2" role="alert">{error}</p>}<button disabled={sending} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-ink px-6 font-semibold text-white transition hover:bg-ink disabled:opacity-60 sm:col-span-2">{sending ? 'Sending…' : 'Send enquiry'} <ArrowRight size={18} /></button><p className="text-xs leading-5 text-stone-500 sm:col-span-2">Your enquiry is delivered through the configured Growth OS email notification service.</p></form>}</div></section>
  </main></MainLayout>
}
