import { ArrowUpRight, CheckCircle2, Clock3 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import ScoreCard from '../../components/common/ScoreCard'
import PageHeader from '../../components/common/PageHeader'
import DashboardLayout from '../../layouts/DashboardLayout'
import { apiGet, apiPost } from '../../lib/api'

export default function Overview() {
  const [data, setData] = useState(null)
  const [analytics, setAnalytics] = useState(null)
  const [leads, setLeads] = useState(null)
  const [recommendations, setRecommendations] = useState([])
  const [locations, setLocations] = useState([])
  const [error, setError] = useState('')
  const [syncing, setSyncing] = useState(false)
  const navigate = useNavigate()
  useEffect(() => {
    Promise.all([
      apiGet('/api/dashboard'),
      apiGet('/api/analytics/overview').catch(() => ({ configured: false })),
      apiGet('/api/leads/summary').catch(() => ({ configured: false, summary: {} })),
      apiGet('/api/recommendations').catch(() => ({ rows: [] })),
      apiGet('/api/search-console/countries').catch(() => ({ rows: [] })),
    ]).then(([dashboard, analyticsData, leadsData, recommendationData, locationData]) => { setData(dashboard); setAnalytics(analyticsData); setLeads(leadsData); setRecommendations(recommendationData.rows || []); setLocations(locationData.rows || []) }).catch((requestError) => setError(requestError.message))
  }, [])
  const scores = useMemo(() => {
    const health = data?.health ?? 0; const visibility = data?.visibility ?? 0
    return [{ label: 'Search health', score: health, change: data?.source === 'google-search-console' ? 'Calculated from live data' : data ? 'Connect Search Console' : 'Loading…', tone: 'emerald' }, { label: 'SEO signal', score: visibility, change: data?.source === 'google-search-console' ? 'Live Search Console' : 'Not connected', tone: 'orange' }, { label: 'GEO readiness', score: data?.geo ?? 0, change: data?.crawl ? 'Live crawl signal' : 'Run a crawl', tone: 'sky' }, { label: 'AEO readiness', score: data?.aeo ?? 0, change: data?.crawl ? 'Live crawl signal' : 'Run a crawl', tone: 'amber' }]
  }, [data])
  const selectedWebsite = data?.websites?.find((website) => data?.siteUrl && (website.siteUrl === data.siteUrl || website.url === data.siteUrl)) || data?.websites?.[0]
  const websiteName = selectedWebsite?.name || 'your website'
  const trend = data?.trend || []; const maxTrendClicks = Math.max(1, ...trend.map((point) => Number(point.overview?.clicks || 0)))
  const runAudit = async () => { setSyncing(true); setError(''); try { const websites = data?.websites || (await apiGet('/api/websites')).websites || []; const matching = (data?.siteUrl ? websites.find((website) => (website.siteUrl === data.siteUrl || website.url === data.siteUrl) && /^https?:/i.test(website.url)) : websites.find((website) => /^https?:/i.test(website.url))); const actions = []; if (matching) actions.push(apiPost(`/api/websites/${matching.id || matching._id}/crawl`)); if (data?.source === 'google-search-console') actions.push(apiPost('/api/search-console/sync')); if (!actions.length) throw new Error('Connect Search Console or add a crawlable website before running an audit.'); const results = await Promise.allSettled(actions); const failed = results.find((result) => result.status === 'rejected'); if (failed) throw failed.reason; const refreshed = await apiGet('/api/dashboard'); setData(refreshed) } catch (requestError) { setError(requestError.message) } finally { setSyncing(false) } }
  return <DashboardLayout><PageHeader eyebrow="Search Console workspace" title="Your online growth score" description={`Website health and visibility for ${websiteName}.`} action={<button onClick={runAudit} disabled={syncing} className="rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white">{syncing ? 'Syncing…' : 'Run a new audit'}</button>} />
    {error && <div className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{error}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{scores.map((score) => <ScoreCard key={score.label} {...score} />)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><article className="panel p-6"><div className="flex items-center justify-between"><div><p className="metric-label">Growth performance</p><h2 className="mt-1 text-xl font-bold">Traffic and conversion signal</h2></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-600">{data?.source === 'google-search-console' ? 'Live Search Console' : 'Not connected'}</span></div><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-5">{[[data?.clicks?.toLocaleString() || '—','Google clicks'],[data?.impressions?.toLocaleString() || '—','Impressions'],[leads?.summary?.lead?.count ?? '—','Leads'],[data?.calls ?? '—','Calls'],[data ? `${Number(data.ctr || 0).toFixed(2)}%` : '—','CTR']].map(([value,label]) => <div key={label}><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div><div className="mt-8 flex h-28 items-end gap-2 rounded-xl bg-slate-50 px-4 py-3">{trend.length ? trend.slice(-14).map((point, index) => <div key={`${point.syncedAt}-${index}`} className="group relative flex-1" title={`${point.overview?.clicks || 0} clicks`}><div className="w-full rounded-t bg-lime-300 transition group-hover:bg-lime-400" style={{ height: `${Math.max(8, Math.round((Number(point.overview?.clicks || 0) / maxTrendClicks) * 100))}%` }} /></div>) : <p className="m-auto text-center text-sm text-slate-500">Daily trend history will appear after the first scheduled sync.</p>}</div><p className="mt-3 text-xs text-slate-500">Search Console window: last 28 days{data?.syncedAt ? ` · synced ${new Date(data.syncedAt).toLocaleString()}` : ''} · {trend.length} saved syncs</p></article>
      <article className="panel p-6"><p className="metric-label">Estimated opportunity</p><p className="mt-2 text-4xl font-bold">{data?.estimatedOpportunity?.value?.toLocaleString() || '—'}<span className="text-base font-medium text-slate-400"> potential clicks</span></p><p className="mt-3 text-sm leading-6 text-slate-500">{data?.estimatedOpportunity?.basis || 'Calculated after live Search Console data is available.'}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="font-bold">{analytics?.configured ? Number(analytics.sessions || 0).toLocaleString() : '—'}</p><p className="text-slate-500">GA4 sessions</p></div><div><p className="font-bold">{analytics?.configured ? Number(analytics.revenue || 0).toLocaleString() : (leads?.summary?.sale?.value ? `$${Number(leads.summary.sale.value).toLocaleString()}` : '—')}</p><p className="text-slate-500">Sales/revenue</p></div></div><p className="mt-3 text-xs text-slate-500">{analytics?.configured ? 'Google Analytics 4 · last 28 days' : leads?.configured ? 'CRM webhook data · configure GA4 for traffic' : 'Connect GA4 or CRM to show live business outcomes.'}</p><button onClick={() => navigate('/dashboard/recommendations')} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-stone-500">Explore opportunities <ArrowUpRight size={16}/></button></article></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><article className="panel p-6"><h2 className="font-bold">Priority actions</h2><div className="mt-4 space-y-3">{(recommendations.length ? recommendations.slice(0, 4) : (data?.alerts || []).slice(0, 4)).map((item, index) => { const task = item.name || item.label; const area = item.area || 'Connection'; const impact = item.impact || 'Required'; return <div key={`${task}-${index}`} className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div className="flex gap-3"><CheckCircle2 size={18} className="mt-0.5 text-stone-500"/><div><p className="text-sm font-semibold">{task}</p><p className="mt-1 text-xs text-slate-500">{area} · {impact}</p>{item.evidence && <p className="mt-1 text-xs text-slate-400">{item.evidence}</p>}</div></div><button onClick={() => navigate(item.target || '/dashboard/recommendations')} className="text-sm font-semibold text-stone-500">Review</button></div> })}{!recommendations.length && !data?.alerts?.length && <p className="text-sm text-slate-500">No priority actions are waiting.</p>}</div></article><article className="panel p-6"><h2 className="font-bold">Current automated tasks</h2><div className="mt-4 space-y-4 text-sm">{(data?.tasks || []).map((task) => <p key={task.label} className="flex gap-3"><Clock3 size={17} className={task.status === 'complete' ? 'text-emerald-500' : task.status === 'needs_connection' ? 'text-amber-500' : 'text-sky-500'}/>{task.label}</p>)}</div></article></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><article className="panel p-6"><h2 className="font-bold">Changes this week</h2><div className="mt-4 space-y-3">{(data?.changesThisWeek || []).map((change) => <div key={`${change.label}-${change.at}`} className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-3 text-sm"><div><p className="font-semibold">{change.label}</p><p className="mt-1 text-xs text-slate-500">{change.source}</p></div><span className="text-xs text-slate-500">{change.at ? new Date(change.at).toLocaleString() : 'Awaiting data'}</span></div>)}</div></article><article className="panel p-6"><h2 className="font-bold">Alerts requiring attention</h2><div className="mt-4 space-y-3">{(data?.alerts || []).map((alert) => <button key={alert.label} type="button" onClick={() => navigate(alert.target || '/dashboard/settings')} className="block w-full rounded-xl border border-amber-100 bg-amber-50 p-3 text-left text-sm text-amber-900"><span className="font-semibold">{alert.label}</span><span className="mt-1 block text-xs font-bold uppercase tracking-wide">{alert.action}</span></button>)}{!data?.alerts?.length && <p className="text-sm text-slate-500">No alerts requiring attention.</p>}</div></article></section>
    <section className="mt-6"><article className="panel p-6"><h2 className="font-bold">Performance by location</h2><p className="mt-1 text-sm text-slate-500">Countries from the latest Search Console window.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{locations.slice(0, 6).map((row, index) => <div key={`${row.keys?.[0] || 'location'}-${index}`} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><span className="font-semibold">{row.keys?.[0] || 'Unknown'}</span><span className="text-right text-slate-500">{Number(row.clicks || 0).toLocaleString()} clicks<br />{Number(row.impressions || 0).toLocaleString()} impressions</span></div>)}</div>{!locations.length && <p className="mt-4 text-sm text-slate-500">Connect Search Console to load location performance.</p>}</article></section>
  </DashboardLayout>
}
