import { ArrowUpRight, CheckCircle2, ExternalLink, RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import DashboardLayout from '../../layouts/DashboardLayout'
import PageHeader from '../../components/common/PageHeader'
import { apiGet, apiPost } from '../../lib/api'

const fallback = { source: 'not-connected', siteUrl: null, clicks: 0, impressions: 0, ctr: 0, position: 0 }

export default function SearchVisibility() {
  const [data, setData] = useState(fallback); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [properties, setProperties] = useState([]); const [selectedProperty, setSelectedProperty] = useState(''); const [queries, setQueries] = useState([]); const [pages, setPages] = useState([]); const [params, setParams] = useSearchParams()
  const load = async () => {
    setLoading(true)
    const [overview, queryData, pageData] = await Promise.allSettled([apiGet('/api/search-console/overview'), apiGet('/api/search-console/queries'), apiGet('/api/search-console/pages')])
    if (overview.status === 'fulfilled') setData(overview.value); else setMessage('Connect a verified Search Console property to load live performance.')
    if (queryData.status === 'fulfilled') setQueries(queryData.value.rows || [])
    if (pageData.status === 'fulfilled') setPages(pageData.value.rows || [])
    if (overview.status === 'rejected' && queryData.status === 'rejected' && pageData.status === 'rejected') { setQueries([]); setPages([]) }
    setLoading(false)
  }
  const loadProperties = async () => { try { const response = await apiGet('/api/search-console/properties'); setProperties(response.properties || []); if (response.properties?.length === 1) setSelectedProperty(response.properties[0].siteUrl) } catch { /* connect action explains the next step */ } }
  useEffect(() => { load(); loadProperties(); if (params.get('connected') === '1') setMessage('Google connected. Select a verified Search Console property to load live data.') }, [])
  const selectProperty = async (event) => { event.preventDefault(); if (!selectedProperty) return; try { await apiPost('/api/search-console/connect', { siteUrl: selectedProperty }); params.delete('connected'); setParams(params); setMessage('Property connected. Loading live Search Console data…'); await load() } catch (error) { setMessage(error.message) } }
  const sync = async () => { try { await apiPost('/api/search-console/sync'); setMessage('Search Console sync completed.'); await load() } catch (error) { setMessage(error.message) } }
  const connectGoogle = async () => { setMessage('Opening Google authorization…'); try { const response = await apiGet('/api/auth/google'); window.location.href = response.url } catch (error) { setMessage(error.message) } }
  const rowValue = (row, index) => row.keys?.[index] || '—'
  return <DashboardLayout><PageHeader eyebrow="Search Console connection" title="Search visibility" description="Use real Google Search Console data to understand how people find your website." action={<div className="flex flex-wrap gap-2"><button onClick={sync} className="inline-flex items-center gap-2 rounded-xl border border-stone-200 px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16} /> Sync</button><button onClick={connectGoogle} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white">Connect Google <ExternalLink size={16} /></button></div>} />
    {message && <div className="mb-6 rounded-xl border border-lime-200 bg-lime-50 px-4 py-3 text-sm text-stone-700" role="status">{message}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Clicks', data.clicks?.toLocaleString() || '—'], ['Impressions', data.impressions?.toLocaleString() || '—'], ['Average CTR', data.ctr != null && data.source !== 'not-connected' ? `${Number(data.ctr).toFixed(2)}%` : '—'], ['Average position', data.position ? Number(data.position).toFixed(1) : '—']].map(([label, value]) => <article className="panel p-5" key={label}><p className="metric-label">{label}</p><p className="mt-3 text-3xl font-bold">{loading ? '…' : value}</p><p className="mt-2 text-xs text-slate-500">Last 28 days · {data.source === 'not-connected' ? 'Not connected' : data.source}</p></article>)}</section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article className="panel p-6"><div className="flex items-start justify-between gap-4"><div><p className="metric-label">Connected property</p><h2 className="mt-2 text-xl font-bold">{data.source === 'not-connected' ? 'No property selected' : data.siteUrl}</h2></div><CheckCircle2 className={data.source === 'not-connected' ? 'text-amber-500' : 'text-emerald-600'} /></div><p className="mt-4 text-sm leading-6 text-slate-500">{data.source === 'not-connected' ? 'Choose a verified property to load live Search Console performance. No placeholder metrics are shown.' : 'Live data is connected, cached in MongoDB, and ready for reporting.'}</p>{properties.length > 0 ? <form onSubmit={selectProperty} className="mt-5 flex flex-col gap-3 sm:flex-row"><select aria-label="Select Search Console property" value={selectedProperty} onChange={(event) => setSelectedProperty(event.target.value)} className="min-h-11 flex-1 rounded-xl border border-stone-200 bg-white px-3 text-sm"><option value="">Select a verified property</option>{properties.map((property) => <option key={property.siteUrl} value={property.siteUrl}>{property.siteUrl}</option>)}</select><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white">Use property <ArrowUpRight size={16} /></button></form> : <button onClick={connectGoogle} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-stone-500">{data.source === 'not-connected' ? 'Connect Google' : 'Reconnect Google'} <ArrowUpRight size={16} /></button>}</article><article className="panel p-6"><p className="metric-label">What this powers</p><ul className="mt-4 space-y-3 text-sm text-slate-600"><li>• Growth score and visibility trend</li><li>• Query and page opportunities</li><li>• Plain-language recommendations</li><li>• Client report comparisons</li></ul></article></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><article className="panel overflow-hidden"><div className="border-b border-stone-100 p-5"><p className="metric-label">Top queries</p><h2 className="mt-1 font-bold">What people searched</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Query</th><th className="p-4">Clicks</th><th className="p-4">Position</th></tr></thead><tbody>{queries.slice(0, 8).map((row, index) => <tr key={`${rowValue(row, 0)}-${index}`} className="border-b last:border-0"><td className="p-4 font-medium">{rowValue(row, 0)}</td><td className="p-4">{row.clicks ?? '—'}</td><td className="p-4">{row.position ? Number(row.position).toFixed(1) : '—'}</td></tr>)}</tbody></table>{!queries.length && <p className="p-5 text-sm text-slate-500">Connect a property to load queries.</p>}</div></article><article className="panel overflow-hidden"><div className="border-b border-stone-100 p-5"><p className="metric-label">Top pages</p><h2 className="mt-1 font-bold">Pages receiving visibility</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Page</th><th className="p-4">Clicks</th><th className="p-4">Impressions</th></tr></thead><tbody>{pages.slice(0, 8).map((row, index) => <tr key={`${rowValue(row, 0)}-${index}`} className="border-b last:border-0"><td className="max-w-xs truncate p-4 font-medium">{rowValue(row, 0)}</td><td className="p-4">{row.clicks ?? '—'}</td><td className="p-4">{row.impressions ?? '—'}</td></tr>)}</tbody></table>{!pages.length && <p className="p-5 text-sm text-slate-500">Connect a property to load pages.</p>}</div></article></section>
  </DashboardLayout>
}
